Добавлен пропс для дропдаунов из необычных мест, например если дропдаун в модалке
timepad/front-components pull request #106
Opened 2022-02-17 09:08 UTC by mauta

1. [new] прикидываем пропс сквозь дропдаун до попапа

https://timepad.myjetbrains.com/youtrack/issue/AF-394

2022-02-18 09:06 UTC, nikolay-komarov requested changes

2022-02-18 09:06 UTC, nikolay-komarov commented on src/components/popup/index.tsx
> +            customPopupId,
а если тут передать `'popup-root'` по-умолчанию - нужны ли будут дополнительные проверки внутри?

2022-02-18 12:11 UTC, mauta commented on src/components/dropdown/Dropdown.tsx
> +    customPopupId,
поменяла везде

[commit](https://github.com/timepad/front-components/pull/106/commits/8e23fd612faa9c259ec69e778a74c3234a85e270)

2022-02-18 12:12 UTC, mauta commented on src/components/popup/index.tsx
> +        const currentPopupId = customPopupId ? customPopupId : 'popup-root';
да, хорошая мысль - [готово](https://github.com/timepad/front-components/pull/106/commits/8e23fd612faa9c259ec69e778a74c3234a85e270)

2022-02-18 12:15 UTC, mauta commented on src/components/popup/index.tsx
> +            customPopupId,
вынесла всё в getRootPopup [commit](https://github.com/timepad/front-components/pull/106/commits/8e23fd612faa9c259ec69e778a74c3234a85e270)

2022-02-18 14:56 UTC, nikolay-komarov approved these changes

2022-03-02 11:22 UTC, d1javu approved these changes

2022-03-02 11:23 UTC, merged