Создать компонент Pagination в репозитоии front-components
timepad/front-components pull request #15
Opened 2021-03-29 11:22 UTC by andruxacomm

1. [new] Компонент пагинация с дочерними компонентами

https://timepad.myjetbrains.com/youtrack/issue/MON-93

2021-03-31 13:33 UTC, andruxacomm commented on src/components/pagination/Pagination.stories.tsx
> +                <Pagination activePage={16} total={999} theme="dark">
можно хук сделать

2021-04-02 15:18 UTC, ru-web-designer requested changes

2021-04-02 15:18 UTC, ru-web-designer commented on src/assets/svg/48/shape-left.svg
> +<svg width="48" height="48" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
Кажется он должен называться `src/assets/svg/48/shape-left-48.svg`

2021-04-02 15:18 UTC, ru-web-designer commented on src/assets/svg/48/shape-right.svg
> +<svg width="48" height="48" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
аналогично

2021-04-02 15:18 UTC, ru-web-designer commented on src/components/pagination/Item.tsx
> +    const isActive = useMemo<boolean>(() => {
```suggestion
    const isActive = useMemo<boolean>(() => activePage === page, [page, activePage]);
```

2021-04-02 15:18 UTC, ru-web-designer commented on src/components/pagination/Item.tsx
> +    const isActive = useMemo<boolean>(() => {
Это же стрелочка

2021-04-02 15:18 UTC, ru-web-designer commented on src/components/pagination/Item.tsx
> +        return cx(
тут тоже можно без return обойтись

2021-04-02 15:18 UTC, ru-web-designer commented on src/components/pagination/Pagination.stories.tsx
> +                    <Pagination.Container>
ну это так себе аргумент, судя по дизайну — все кнопки пагинации могут быть доченими элементами одного большого flex-контейнера

2021-04-02 15:18 UTC, ru-web-designer commented on src/components/pagination/Pagination.stories.tsx
> +                <Pagination activePage={16} total={999} theme="dark">
Не, я не совсем об этом, я скорее о том, чтоб можно было написать без children
```typescript
<Pagination activePage={16} total={999} theme="dark"/>
```
и компонент бы понял, что ему ничего не передано и сам бы нарисовал все внутренности по алгоритму определённому, типа "две страницы влево, две вправо, всегда пусть будет первая и последняя" и т.п.

2021-04-03 07:45 UTC, andruxacomm commented
![image](https://user-images.githubusercontent.com/40542655/113472142-68329b00-947a-11eb-980b-2d9c73feb966.png)

2021-04-05 13:15 UTC, ru-web-designer commented on src/components/pagination/Pagination.stories.tsx
> +                    <Pagination.Container>
почему не сделать марджин prev и next и убрать его из вёрстки вообще?

2021-04-05 13:15 UTC, ru-web-designer commented on src/components/pagination/Pagination.stories.tsx
> +                    <Pagination.Container>
эта ветка упорно игнорируется )

2021-04-05 14:46 UTC, ru-web-designer approved these changes

2021-06-02 14:32 UTC, NickJ1984 commented
А почему `package-lock.json` изменился, зависимости ведь не менялись? 
Предлагаю выпилить его из PR'a

2021-06-02 14:35 UTC, NickJ1984 commented on src/components/pagination/Ellipsis.tsx
> +    const buttonClassName = useMemo<string>(() => cx(component('pagination', 'ellipsis')(), className), [className]);
а зачем это в `useMemo` обернуто?

2021-06-02 14:42 UTC, NickJ1984 commented on src/components/pagination/Pagination.tsx
> +    onChange,
сюда можно дописать дефолтное значение:
`onChange = defaultChange,`
и не втыкать его ниже по коду

2021-06-02 14:44 UTC, NickJ1984 commented on src/components/pagination/usePagination.ts
> +    const centerItems = useMemo<TPage[]>(() => {
В этом компоненте `useMemo` вполне оправдан

2021-06-10 13:07 UTC, NickJ1984 approved these changes

2021-06-17 12:06 UTC, ru-web-designer approved these changes

2021-06-17 12:09 UTC, merged