Компонент dropdown и списка
timepad/front-components pull request #23
Opened 2021-04-23 13:52 UTC by a-burenkov-timepad

1. [new] Новый компонент dropdown
2. [new] Новый компонент списк / меню
https://timepad.myjetbrains.com/youtrack/issue/PL-202

2021-04-30 14:17 UTC, ru-web-designer requested changes

2021-04-30 14:17 UTC, ru-web-designer commented on src/components/dropdown/DropDown.stories.tsx
> +const DropBtn = ({...props}) => {
блин серьёзно? а чем просто (props) не угодил?

2021-04-30 14:17 UTC, ru-web-designer commented on src/components/dropdown/DropDown.stories.tsx
> +const DropBtn = ({...props}) => {
Типизируй через FC

2021-04-30 14:17 UTC, ru-web-designer commented on src/components/dropdown/DropDown.stories.tsx
> +                    <List mod={'dark'}>
mod это что? modifier? mode? я бы назвал как-то конкретнее, color или variant или theme

2021-04-30 14:17 UTC, ru-web-designer commented on src/components/dropdown/ToggleButton.tsx
> +interface IToggleButton
Кажется этот компонент всё-таки должен рендерить кнопку из UI-кита, чтоб мы могли пользоваться всей её мощью

2021-05-12 09:34 UTC, a-burenkov-timepad commented on src/components/dropdown/DropDown.stories.tsx
> +const DropBtn = ({...props}) => {
Думал буду передавать параметры в другие компоненты, но оказалось, что не надо.
Сделал

2021-05-12 09:35 UTC, a-burenkov-timepad commented on src/components/dropdown/DropDown.stories.tsx
> +                    <List mod={'dark'}>
Сменил на variant

2021-05-12 09:38 UTC, a-burenkov-timepad commented on src/components/dropdown/ToggleButton.tsx
> +interface IToggleButton
Поправил. Добавил extends от IButtonProps

2021-05-13 16:37 UTC, ru-web-designer approved these changes

2021-06-30 10:57 UTC, ru-web-designer approved these changes

2021-06-30 10:59 UTC, merged