Добавление компонента Modal
timepad/front-components pull request #27
Opened 2021-05-21 06:44 UTC by rail-ka

1. [new][L] Добавлен компонент Modal со стилями

https://timepad.myjetbrains.com/youtrack/issue/PL-203

2021-05-21 13:07 UTC, ru-web-designer requested changes

2021-05-21 13:07 UTC, ru-web-designer commented on src/components/modal/Modal.tsx
> +                (title ? (
не понял, что это? т.е. модал рисует children если не передан title и рисует WindowComponent если передан?

как-то очень криво

модалы должны быть композиционными, без передачи пропсов, т.е. вот у нас есть пропсы

title
titleIsTransparent
description
headerContent
submitLabel
submitHandler
cancelLabel

и т.п. которые дальше влияют на отобьражение вложенных элементов — это неправильный пусть решения задачи "управлять надписью на кнопочке модала", "передала коллбека кнопочке модала" и т.п.

а что еслти захочу сделать три кнопочки? добавить ещё 3 пропса что ли? нет, 4 — ещё один будет решать "отображать кнопочку или нет".

нет, такое надо решать композицией, вызов модала должен выглядеть не так:

```tsx
<Modal
      title={"Заголовок"}
      titleIsTransparent={titleIsTransparent}
      description={Описание модала}
      headerContent={<h1>Контент заголовка</h1>}
      className={"cmodal--custom-class"}
      overlayClassName={"cmodal__overlay--custom-class"}
      isOpen={true}
      blockCloseOnOutsideClick={false}
      onRequestClose={handleOnRequestClose}
      backHandler={backHandler}
      submitLabel={"Submit"}
      submitHandler={submitHandler}
      submitDisabled={submitDisabled}
      cancelLabel={"Cancel"}
      cancelHandler={cancelHandler}
      cancelDisabled={cancelDisabled}
    />
```

А вот так:

```tsx
<Modal
      className={"cmodal--custom-class"}
      overlayClassName={"cmodal__overlay--custom-class"}
      isOpen={true}
    >
      <Modal.Header>
        <Modal.Title transparent={titleIsTransparent}>Заголовок модала</Modal.Title>
        <Modal.Description>Описание модала</Modal.Description>
      </Modal.Header>
      <Modal.Body>
        Содержимое модала
      </Modal.Body>
      <Modal.Footer>
        <Button type={"submit"} onClick={submitHandler} disabled={submitDisabled}>Submit</Button>
        <Button onClick={cancelHandler} disabled={cancelDisabled}>Cancel</Button>
      </Modal.Footer>
    </Modal>
```

Все пропсы, решающие специфические задачи ДОЧЕРНЫХ компонентов превратились в композицию этих компонентов.

<Modal.Header>, <Modal.Body> и <Modal.Footer> разделяют модал на 3 части. Я не понял зачем существовал одновременно пропс title и headerContent, предполагаю что headerContent рендерился вместо тайтла, когда он был передан. Внутри <Modal.Header> — заголовой и дескрипшен, вместо того чтобы передавать их содержимое через пропсы мы просто пишем его композиционно (и сразу у нас появляется куча возможностей по вёрстке). Внутри <Modal.Body> у нас сожеримое модала. А внутри <Modal.Footer> — кнопки действий, для управлениях которыми раньше нужно было писать шест ьпропсов и при этом мы не могли пользоваться всем тем великолепием кнопочным, которое мы создали ранее (зачем тогда мы его писали?) и не могли добавить ещё кнопок.

На резонный вопрос "а как заменить все модалы в афише, которые написаны по-старому и ожидат эти пропсы" я отвечу — создай спецификацию — это компонент, которые будет принимать все те пропсы, которые принимает старый модал и рендерить внутри себя правильную композицию с этими пропсами. Нназови его типа ModalAdapter, напиши в каментах что он устаревший и призови переписывать его на композицию Modal и его вложенных компонентов (Modal.Description, Modal.Header и т.п.)

2021-05-25 14:52 UTC, ru-web-designer approved these changes

2021-05-27 07:46 UTC, ru-web-designer approved these changes

2021-05-27 08:29 UTC, NickJ1984 approved these changes

2021-06-17 07:00 UTC, NickJ1984 approved these changes

2021-06-17 07:23 UTC, merged