PL-197 Миграция компонента Userpics
timepad/front-components pull request #3
Opened 2021-03-17 05:50 UTC by rail-ka

https://timepad.myjetbrains.com/youtrack/issue/PL-197

2021-03-22 11:20 UTC, olegover requested changes

2021-03-31 09:40 UTC, olegover requested changes

2021-03-31 09:40 UTC, olegover commented on src/components/Userpic/Pic.tsx
> +    let classNames = cx('auserpic', className, {
Мы вроде как отходим от атомарной модели, поэтому записи вида auserpic, сейчас уже считаются ошибкой.
Я не буду в каждом месте прописывать, поищи пожалуйста сам и исправь.

2021-03-31 09:40 UTC, olegover commented on src/components/Userpic/Pic.tsx
> +        'auserpic--interactive': onClick != null,
А здесь именно нестрогое сравнение надо?

2021-03-31 09:40 UTC, olegover commented on src/components/Userpic/Pic.tsx
> +    const bg: CSSProperties | undefined = undefined;
А почему undefined? Есть же unset.

2021-03-31 09:40 UTC, olegover commented on src/components/Userpic/Pic.tsx
> +        <div className={classNames} onClick={onClick} style={bg}>
Судя по коду  после инициализации const bg: CSSProperties | undefined = undefined; не меняется. Так какой в ней смысл?

2021-03-31 09:40 UTC, olegover commented on stories/Elements/helpers.tsx
> +            <span className="t-caption t-caption-16" style={{color: '#808080'}}>
Не проще ли t-caption расширить, или acolor использовать вместо style={{color: '#808080'}}?

2021-03-31 09:40 UTC, olegover commented on stories/Elements/helpers.tsx
> +export const Title = ({children}: PropsWithChildren<unknown>): React.ReactElement => {
А почему именно unknown?

2021-04-01 08:09 UTC, rail-ka commented on src/components/Userpic/Pic.tsx
> +        'auserpic--interactive': onClick != null,
Если onClick может быть только undefined, но не null, думаю можно сделать проверку строгим равенством на undefined, поправлю

2021-04-01 08:11 UTC, rail-ka commented on src/components/Userpic/Pic.tsx
> +    const bg: CSSProperties | undefined = undefined;
тут потому что в 52 строке style property у div элемента может быть `React.CSSProperties | undefined`

2021-04-01 08:14 UTC, rail-ka commented on src/components/Userpic/Pic.tsx
> +        <div className={classNames} onClick={onClick} style={bg}>
Тут действительно не имеет смысла, я тогда просто удалю bg?

2021-04-02 09:49 UTC, rail-ka commented on stories/Elements/helpers.tsx
> +export const Title = ({children}: PropsWithChildren<unknown>): React.ReactElement => {
В коде тут было `PropsWithChildren<{}>`, но у меня ESLint ругается:
`Don't use `{}` as a type. `{}` actually means "any non-nullish value".`
Изменю согласно рекомендации ESLint на `Record<string, never>`

2021-04-05 09:23 UTC, andruxacomm commented on stories/Elements/helpers.tsx
> +export const Title = ({children}: PropsWithChildren<unknown>): React.ReactElement => {
протипизируй как FC лучше

2021-04-05 09:23 UTC, andruxacomm commented on stories/Elements/helpers.tsx
> +export const Title = ({children}: PropsWithChildren<unknown>): React.ReactElement => {
Протипизируй Title как  FC, у фс в пропсах чилдрен есть автоматически

2021-04-12 14:51 UTC, olegover commented on src/components/Userpic/Orgpic.tsx
> +export const Orgpic: React.FC<IProps> = (props) => {
props: IProps не надо писать?

2021-04-12 14:52 UTC, olegover commented on src/components/button/Button.tsx
> +export const Button = (props: IButtonProps): JSX.Element => {
А чего без React.FC?

2021-04-12 14:55 UTC, rail-ka commented on src/components/button/Button.tsx
> +export const Button = (props: IButtonProps): JSX.Element => {
тут у меня typescript ругается, я не стал добавлять, может у кого то получится добавить так чтобы не ругался ts (еще этот компонент не я добавлял, просто поправил на стрелочную)

2021-04-12 14:57 UTC, rail-ka commented on src/components/Userpic/Orgpic.tsx
> +export const Orgpic: React.FC<IProps> = (props) => {
нет, тип у props выводится автоматически

2021-04-12 15:01 UTC, olegover commented on src/services/helpers/SpacerHelper/spacerHelper.ts
> +        return className + `-${size === 0 ? 0 : size || 1}${plusHalf ? '-5' : ''}`;
Возможно я что-то упускаю, но. size === 0 ? 0 : size || 1 станет единицей, только если size === 0, может имеет смысл написать size === 0 ? 1 : size

2021-04-12 15:06 UTC, rail-ka commented on src/services/helpers/SpacerHelper/spacerHelper.ts
> +        return className + `-${size === 0 ? 0 : size || 1}${plusHalf ? '-5' : ''}`;
тут похоже идет проверка на undefined, поменял на более понятную альтернативу: `size ?? 1`
![изображение](https://user-images.githubusercontent.com/9999646/114416695-9cfccb80-9bb9-11eb-87f1-c8272882d77c.png)

2021-04-12 15:37 UTC, olegover commented on src/services/helpers/SpacerHelper/spacerHelper.ts
> +        return className + `-${size === 0 ? 0 : size || 1}${plusHalf ? '-5' : ''}`;
А, если plusHalf true, то условие выполнится и для size, который может быть undefined, понятно. Строкой size быть не может, ну да ладно

2021-04-12 15:38 UTC, olegover commented
Необходимо описать pr в соответствии с правилами

2021-04-12 15:41 UTC, olegover commented on src/components/button/Button.tsx
> +export const Button = (props: IButtonProps): JSX.Element => {
Кнопку трогать вообще не надо было. Договорились эти изменения откатить

2021-04-12 17:01 UTC, olegover approved these changes

2021-04-21 08:32 UTC, NickJ1984 commented on src/components/Userpic/cuserpic.less
> +@import "../../assets/css/bundle.less";
bundle так не стоит импортировать, плюс чтобы стиль `cuserpic` подтянулся в OTP его нужно добавить в `src/assets/css/otp-styles-bundle.less`, вот тут подробнее расписано:
https://www.notion.so/timepaddev/front-components-22822e2750d242749c8f5b93763259d6#1810c48fc6394abe8fafcfcd3c139ca6

2021-04-21 08:34 UTC, NickJ1984 commented on package.json
> +    "@storybook/addon-knobs": "^6.1.21",
А зачем нам кнобы?

2021-04-21 08:39 UTC, NickJ1984 commented on stories/components/StoryTitle.tsx
> +import * as React from 'react';
Уже есть вот тут src/services/helpers/storyBookHelpers/storybookHelpers.tsx

2021-04-21 08:39 UTC, NickJ1984 commented on stories/components/StoryTitle.tsx
> +export const StoryTitle: React.FC = ({children}) => {
StoryTitle уже есть вот тут src/services/helpers/storyBookHelpers/storybookHelpers.tsx

2021-04-21 08:43 UTC, NickJ1984 commented on stories/Elements/helpers.tsx
> +export const Title: React.FC = ({children}) => {
Title не тоже самое что и StoryTitle? Если нет то ей место в src/services/helpers/storyBookHelpers
P.S. Зачем ты сделал папку stories? У нас же тут архитектура отличная от NTP, и напрямую копировать ее (архитектуру) оттуда не стоит.

2021-04-21 08:45 UTC, NickJ1984 commented on stories/Userpic.stories.tsx
> +import '../src/assets/css/bundle.less';
сторисы лежат в папке с компонентом, а не тут

2021-04-21 08:49 UTC, NickJ1984 commented on stories/Userpics.stories.tsx
> +import React from 'react';
Стори компонентов лежат в папке с одноименным компонентом, а не тут

2021-04-21 08:56 UTC, NickJ1984 commented on stories/lib/main.less
> +@import "../../src/assets/css/vars";
Название main, намекает на то что это основной стиль для некоей группы сторей, а встретил я его только в одной... в любом случае можно в папке компонента сделать подпапочку для сторевских вспомогательных стилей

2021-04-21 08:59 UTC, NickJ1984 commented on src/components/utility/Modifiers/Brick.tsx
> +import * as React from 'react';
Это хелпер для сторибука или отдельный компонент не пойму, что за utility/Modifiers?

2021-04-21 09:00 UTC, NickJ1984 commented on src/components/utility/Modifiers/Gap.tsx
> +};
Это хелпер для сторибука или отдельный компонент не пойму, что за utility/Modifiers?

2021-04-21 09:00 UTC, NickJ1984 commented on src/components/utility/Modifiers/Brick.tsx
> +};
Это хелпер для сторибука или отдельный компонент не пойму, что за utility/Modifiers?

2021-04-21 09:01 UTC, NickJ1984 commented on .storybook/main.js
> +    '@storybook/addon-knobs/register', // addon управления параметрами во вкладке,
А зачем нам кнобы?

2021-04-21 09:05 UTC, NickJ1984 commented on src/components/Userpic/Pic.tsx
> +        classNames = cx(classNames, 'cuserpic--pic');
Возможно лучше перевести в const?
```
let classNames = cx('cuserpic', className, {
  'cuserpic--interactive': onClick !== undefined,
  'cuserpic--square': shape === 'square',
  'cuserpic--small': size === 'small',
  'cuserpic--big': size === 'big',
  'cuserpic--bigger': size === 'bigger',
  'cuserpic--biggest': size === 'biggest',
  'cuserpic--pic': !!fillURL
});
```

2021-04-21 14:04 UTC, ru-web-designer requested changes

2021-04-21 14:04 UTC, ru-web-designer commented on src/components/Userpic/Pic.tsx
> +        classNames = cx(classNames, 'cuserpic--pic');
Это вообще должно быть сделано через хелпер component, про это написано тут https://www.notion.so/timepaddev/front-components-22822e2750d242749c8f5b93763259d6#9a26807ba5664c988ceb82bbeb8d0cc5

2021-04-23 08:04 UTC, NickJ1984 commented on src/components/userpic/Orgpic.tsx
> +interface IProps {
Лучше будет заимпортить этот интерфейс из `Pic.tsx`, и использовать здесь, а не просто копировать.

2021-04-23 08:06 UTC, NickJ1984 commented on src/components/userpic/Userpic.tsx
> +interface IProps {
Лучше будет заимпортить этот интерфейс из Pic.tsx, и использовать здесь, а не просто копировать.

2021-04-23 08:24 UTC, NickJ1984 approved these changes

2021-04-23 11:54 UTC, ru-web-designer approved these changes

2021-04-27 11:21 UTC, NickJ1984 commented
В описании PR'a убери ссылку на PR ntp, там должна быть ссылка только на тикет, без всяких пояснений и прочего:
https://www.notion.so/timepaddev/pull-requests-c3fa52a661544e52912651dce566f077#9e2b708f079444d0a85a82c64c8d121b

2021-05-13 14:06 UTC, ru-web-designer approved these changes

2021-05-21 13:39 UTC, ru-web-designer approved these changes

2021-05-21 13:39 UTC, ru-web-designer approved these changes

2021-05-21 13:39 UTC, ru-web-designer approved these changes

2021-05-28 12:02 UTC, NickJ1984 approved these changes

2021-06-04 07:19 UTC, NickJ1984 approved these changes

2021-06-04 07:22 UTC, merged