Запрограммированы Labels and counters для UI-кита
timepad/front-components pull request #36
Opened 2021-07-06 13:33 UTC by lzhabo

1.[new][M] Запрограммированы Labels and Сounters  компоненты для UI-кита
https://timepad.myjetbrains.com/youtrack/issue/TPI-182

2021-07-13 11:40 UTC, olegover requested changes

2021-07-13 11:40 UTC, olegover commented on .gitignore
> +assets/
Папку assets точно не стоит в гитигнор добавлять, как и все остальное

2021-07-13 11:40 UTC, olegover commented on src/components/counter/ccounter.less
> +    .cbadge {
Очень странно что block так сильно меняет поведение другого блока. А cbadge может существовать только внутри block, хотя он и сам  block...
Поддерживать такое будет не просто.
Опять же под размеры шрифтом уже есть переменные, используй пожалуйста их.

2021-07-14 15:19 UTC, olegover requested changes

2021-07-14 15:19 UTC, olegover commented on src/components/counter/Counter.tsx
> +            <div className={cbadge(value == null ? 'empty' : '')}>{value}</div>
const badgeClasses = cx(cn(component('badge')(), value === null ? 'empty' : '')(), 'tsmall')

2021-07-14 15:19 UTC, olegover commented on src/components/counter/Counter.tsx
> +            <div className={cbadge(value == null ? 'empty' : '')}>{value}</div>
Если не передать null явно, то и тебя будет undefined

2021-07-14 15:44 UTC, lzhabo commented on src/components/button/cbtn.less
> +    &:active, &:focus {
![image](https://user-images.githubusercontent.com/52199564/125651445-3edec1d7-5061-446d-9d38-17913e2e482e.png)
Это не мое 😇, мне надо изменения прост заребейзить

2021-07-14 16:22 UTC, lzhabo commented on src/components/counter/Counter.tsx
> +            <div className={cbadge(value == null ? 'empty' : '')}>{value}</div>
при строгой проверке на null у меня не работает, оно не применяет класс empty, одинаково работает при строгой проверке на undefined, но мне кажется что лучше так оставить 
![image](https://user-images.githubusercontent.com/52199564/125657260-ed2acfba-7a31-4f6a-915b-837dfaba8584.png)

2021-07-15 09:55 UTC, olegover commented on src/components/counter/Counter.tsx
> +            <div className={cbadge(value == null ? 'empty' : '')}>{value}</div>
Как раз проблема в самом нестрогом неравенстве. Ты права, value == null действительно вернет try при value = null или undefined. Но это больше хак что ли, хотя и весьма действенный. Замени на строгое сравнение

2021-07-27 14:29 UTC, olegover approved these changes

2021-07-27 14:29 UTC, olegover commented on src/components/label/clabel.less
> +  .t-small();
Мне кажется здесь это ни к чему

2021-07-27 14:31 UTC, lzhabo commented on src/components/label/clabel.less
> +  .t-small();
этого уже тут и нет, я исправила

2021-07-27 14:32 UTC, olegover commented
Оформи pr правильно

2021-08-09 09:17 UTC, olegover approved these changes

2021-08-09 12:18 UTC, olegover submitted a review, later dismissed

2021-09-07 12:19 UTC, ru-web-designer approved these changes

2021-09-09 14:51 UTC, merged