Добавлен компонент Snackbar
timepad/front-components pull request #39
Opened 2021-07-12 10:32 UTC by MarinaKStratosfera

1. [new] Добавлен компонент Snackbar c провайдером
2. [bfx] Добавлен импорт стилей cmodal.less, clogo.less в otp-styles-bundle.less
https://timepad.myjetbrains.com/youtrack/issue/TPI-187

2021-07-15 16:04 UTC, olegover requested changes

2021-07-15 16:04 UTC, olegover commented on src/components/snackbar/useSnackbar.ts
> +    const {openSnackbar, closeSnackbar = () => null} = useContext(SnackbarContext);
Вроде  можно писать просто null вместо () => null

2021-07-16 07:17 UTC, MarinaKStratosfera commented on src/components/snackbar/SnackbarProvider.tsx
> +                triggerSnackbar(snackbarProps);
В этом случае не надо, это таймер отрисовки следующего вызванного снекбара

2021-07-16 07:23 UTC, MarinaKStratosfera commented on src/components/snackbar/csnackbar.less
> +  > button, > button:active {
Исправила

2021-07-16 12:32 UTC, olegover approved these changes

2021-08-03 17:30 UTC, merged