Добавлен classname для Radio
timepad/front-components pull request #42
Opened 2021-07-20 11:42 UTC by MarinaKStratosfera

1. [ref] Добавлен classname для Radio
https://timepad.myjetbrains.com/youtrack/issue/MON-166

2021-07-20 12:47 UTC, olegover commented on src/components/forms/Radio/Radio.tsx
> +    className,
Допиши здесь "", className=""

2021-07-20 12:47 UTC, olegover commented on src/components/forms/Checkbox/Checkbox.tsx
> +    className,
Допиши здесь "", className=""

2021-07-20 14:06 UTC, olegover approved these changes

2021-08-10 13:38 UTC, olegover requested changes

2021-08-10 13:38 UTC, olegover commented on src/components/forms/Checkbox/Checkbox.tsx
> +    blue = 'blue',
Не очень понятна логика именования primary и blue.

2021-08-10 13:38 UTC, olegover commented on src/components/forms/Radio/Radio.tsx
> +export enum RadioVariant {
Не очень понятна логика именования primary и blue.

2021-08-10 13:38 UTC, olegover commented on src/components/forms/Checkbox/ccheckbox.less
> +      background-color: @c-light-blue !important;
А important здесь точно нужен? Просто в src/components/forms/Radio/cradio.less его нет.

2021-09-22 10:24 UTC, ru-web-designer approved these changes

2021-09-22 10:26 UTC, merged