Добавлен компонент Banner
timepad/front-components pull request #43
Opened 2021-07-21 12:12 UTC by Dostoynov

1. [new][M] Добавлен комнент Banner
2. [ref][S] Теперь у баннера есть только одна тема - желтая. Выбрать тему больше нельзя.
3. [new][S] Баннеру можно прокинуть svg иконку. Если прокинуть icon={true} то будет выбрана иконка по дефолту.
4. [new][S] Появился флаг closeable. Если true, то баннер можно закрыть.

https://timepad.myjetbrains.com/youtrack/issue/TPI-196

2021-07-21 15:55 UTC, olegover requested changes

2021-07-21 15:55 UTC, olegover commented on src/components/row/crow.less
> +  html body .mtheme--darkpic & {
Во первых не надо злоупотреблять вложенностью.
Во вторых не очень понятно во что развернется 
html body .mtheme--darkpic & 
в html body .mtheme--darkpic .crow__outer? 
А зачем такая специфичность (html body )?
А почему именно crow__outer переопределяет поведение .crow:active, те элемент переопределяет поведение блока...это немного странно.

2021-07-21 15:55 UTC, olegover commented on src/components/row/crow.less
> +      &, &:active, .crow__body .crow__body__caption {
По бэму crow__body__caption  получается элемент элемента, такого быть не может
crow__body или crow__caption.
С другой стороны раньше для задания цвета использовался атомарный класс, возможно имеет смысл добавить, но это на усмотрение разработчика

2021-07-21 15:55 UTC, olegover commented on src/components/row/crow.less
> +    &, &:active, .crow__body .crow__body__caption {
элемент элемента, такого быть не может

2021-07-21 15:55 UTC, olegover commented on src/components/row/crow.less
> +    .crow__body__text, .crow__body__caption {
элемент элемента, такого быть не может

2021-07-21 15:55 UTC, olegover commented on src/components/row/crow.less
> +      line-height: 22px;
Необходимо использовать типографику, t-caption, t-body, и прочее

2021-07-21 15:55 UTC, olegover commented on src/components/row/crow.less
> +        font-size: 13px;
Необходимо использовать типографику, t-caption, t-body, и прочее

2021-08-09 12:05 UTC, olegover requested changes

2021-08-09 12:05 UTC, olegover commented on src/components/banner/Banner.tsx
> +    const Icon = () => {
Мне кажется, что  Icon можно вынести в отдельный компонент.

2021-10-01 16:46 UTC, d1javu requested changes

2021-10-01 16:46 UTC, d1javu commented on src/components/banner/Banner.tsx
> +    const Icon = () => {
Он в принципе излишний, а ниже сломана логика. Блок проверяется на icon, а значит не может быть показана другая иконка, кроме icon. 
```
{icon && (
   <Row.Icon className={component('banner', 'icon')()}>
       <Icon />
    </Row.Icon>
)}
```

2021-10-01 16:46 UTC, d1javu commented on src/components/banner/Banner.tsx
> +    const BodyStyle = {paddingLeft: icon ? 0 : '16px', paddingRight: closeable ? 0 : '16px'};
Row  уже обновился и стал мультистрочным

2021-10-01 16:46 UTC, d1javu commented on src/components/banner/Banner.tsx
> +            return <props.icon />;
здесь про почему props.icon, а не icon

2021-10-01 16:46 UTC, d1javu commented on src/components/banner/cbanner.less
> +  svg.cicon * {
Используется класс за пределами скоупа этого файла

2021-10-01 16:46 UTC, d1javu commented on src/components/banner/Banner.tsx
> +    withIcon?: boolean;
Мне кажется лучше убрать вообще проп withIcon вообще, и сделать кастом на основе базового компонента
```
export InfoBanner = (props) => <Banner {...props} icon={<InfoIcon />} />

```

2021-10-04 14:39 UTC, Dostoynov commented on src/components/banner/Banner.tsx
> +    const Icon = () => {
Действительно, глупость написал. Исправил.

2021-10-04 14:43 UTC, Dostoynov commented on src/components/banner/Banner.tsx
> +    const BodyStyle = {paddingLeft: icon ? 0 : '16px', paddingRight: closeable ? 0 : '16px'};
True, исправил

2021-10-04 14:51 UTC, Dostoynov commented on src/components/banner/cbanner.less
> +  svg.cicon * {
Поправил

2021-10-04 14:53 UTC, Dostoynov commented on src/components/banner/Banner.tsx
> +    withIcon?: boolean;
Сделал тип icon svg | boolean. Соответсвенно если boolean то стандартная иконка, иначе та что передана. withIcon убрал

2021-10-05 11:58 UTC, d1javu commented on src/components/banner/Banner.tsx
> +    withIcon?: boolean;
Мы уже обговаривали этот вариант, и отказались от него. Не стоит делать проп icon то булевой, то svg. Для баннера с информационной иконкой, как для частого сценария, я предложил сделать частный случай в виде компонента InfoBanner (основанного на Banner). Так мы не будем усложнять Banner, и избежим кучи условий.

2021-10-05 12:00 UTC, d1javu commented on src/components/banner/cbanner.less
> +  svg.cicon * {
Не переменная, а класс cicon. Нет возможности избежать его использования?

2021-10-12 11:28 UTC, Dostoynov commented on src/components/banner/cbanner.less
> +  svg.cicon * {
Сделал ```button svg *```

2021-11-02 10:21 UTC, d1javu approved these changes

2021-11-03 08:18 UTC, merged