TPI-235 Обновление компонента Logo: расширяемая версия, рефакторинг
timepad/front-components pull request #49
Opened 2021-08-23 16:05 UTC by pgalkevich

1. [new][M] Добавлена расширяемая из краткой в полную версия логотипа.
2. [ref][S] в Logo.tsx отрефакторен код: убран лишний код, удалены лишние импорты. 

https://timepad.myjetbrains.com/youtrack/issue/TPI-235

2021-09-07 12:54 UTC, ru-web-designer submitted a review, later dismissed

2021-09-30 16:02 UTC, Volchunovich requested changes

2021-09-30 16:02 UTC, Volchunovich commented on src/components/logo/Logo.tsx
>              </div>
Ты уверен, что здесь необходимо делать двойную вложенность контейнеров?

Ты можешь попробовать написать
```ts
const finalClassNames = component('logo')({
  expandable: action === 'expandable',
  hoverable: action === 'hoverable',
});
```
и тогда внутри стилей можешь написать с аннотацией бэм 2 модификатора
```css
&--expandable, &--hoverable { .. }
```

и просто повесить на один блок div 
```
<div className={finalClassNames}>
...
</div>
```

2021-09-30 16:35 UTC, pgalkevich commented on src/components/logo/Logo.tsx
> +    color?: Colors | '';
Бес попутал.. Убрано.

2021-09-30 16:37 UTC, pgalkevich commented on src/components/logo/Logo.tsx
>      const className = component('logo')();
спорный момент, но ввиду решения вопроса ниже (про излишнюю вложенность) необходимость такого подхода уже очевидна.

2021-09-30 16:37 UTC, pgalkevich commented on src/components/logo/Logo.tsx
>              </div>
Ты прав. Поправил.

2021-10-01 11:14 UTC, ru-web-designer commented on src/components/logo/Logo.tsx
>      const className = component('logo')();
@Volchunovich не не не, у нас договорённость писать через component в любом случае
это момент дисциплины именовния

2021-10-01 11:20 UTC, ru-web-designer commented on src/components/logo/Logo.tsx
>              </div>
А, ну это ок

2021-10-07 12:18 UTC, ru-web-designer approved these changes

2021-10-07 12:28 UTC, merged