TPI-236 Компонент Suggest.
timepad/front-components pull request #51
Opened 2021-09-01 10:36 UTC by pgalkevich

1. [new][L] Добавлен компонент Suggest - поле ввода (на основе компонента Input) с подсказкой ввода.

2021-09-30 17:21 UTC, Volchunovich requested changes

2021-09-30 17:21 UTC, Volchunovich commented on src/components/suggest/SuggestList.tsx
> +            ))}
Я думаю стоит это переписать на новый Row. Там уже все готово по дизайну, тебе нужно написать только
```ts
<Row hoverable>
  <Row.Text>any text</Row.Text>
  <Row.Caption>any caption</Row.Caption>
<Row>
```
это избавит тебя от лишних стилей и дополнительной какой-то логики

2021-09-30 17:21 UTC, Volchunovich commented on src/components/suggest/Suggest.tsx
> +import {Input, IInputProps} from '../forms/Input/Input';
Используй новый компонент TextLight, который лежит в папке ```form```, ибо старый Input не соответствует дизайну и мы планируем избавиться от него. Новый TextLight такой же и содержит необходимый тебе функционал.

2021-10-01 15:52 UTC, pgalkevich commented on src/components/suggest/SuggestList.tsx
> +            ))}
если заменить элементы списка на компонент Row, то реализация дропдауна отклоняется от макета и требуется дополнительная стилизация и доработки.
скрин приложил в тикете

2021-10-01 16:46 UTC, pgalkevich commented on src/components/suggest/Suggest.tsx
> +import {Input, IInputProps} from '../forms/Input/Input';
Заменен.

2021-10-01 23:51 UTC, Volchunovich approved these changes

2021-10-07 19:56 UTC, Volchunovich approved these changes

2021-10-12 12:58 UTC, ru-web-designer commented on src/components/suggest/Suggest.tsx
> +    const fetchData = (url: string): void => {
да блин вы что, это же гон
Suggest должен принимать async function пропс (fetchAsync например), которая должна возвращать промис, который резолвиться в интерфейс данных саджеста ISuggestion либо реджектиться в ошибку
мы же так привязываемся к определённому формату с бекенда
а ещё там ниже ```.catch(() => setSearchData([]))``` ну супер ваще, а если у нас ошибка соединения? как мы вообще можем что-то обработать так?

как варианты можно оставить пропс url, но сделать его опциональным и обязательно добавить опционнальный fetchAsync

2021-11-01 16:26 UTC, pgalkevich commented on src/components/suggest/Suggest.tsx
> +    const fetchData = (url: string): void => {
Заменил на функцию. url убрал

2021-11-01 18:16 UTC, Volchunovich approved these changes

2021-11-02 11:23 UTC, ru-web-designer approved these changes

2021-11-02 13:37 UTC, merged