Поправлен паддинг текста снизу у Form.TextLight
timepad/front-components pull request #73
Opened 2021-12-02 11:58 UTC by aekostyuk

1. [bfx] Увеличен паддинг текста снизу для соответствия макетам

https://timepad.myjetbrains.com/youtrack/issue/PL-301

2022-01-28 14:01 UTC, ru-web-designer submitted a review, later dismissed

2022-01-28 15:24 UTC, nikolay-komarov requested changes
обсудили, посмотреть на перенос длинных слов в caption

2022-01-28 15:37 UTC, aekostyuk commented
> обсудили, посмотреть на перенос длинных слов в caption

добавлен перенос

2022-01-28 15:48 UTC, nikolay-komarov approved these changes

2022-01-31 11:14 UTC, ru-web-designer approved these changes

2022-02-04 12:58 UTC, merged