Добавил композицию компонентов табов со стилями
timepad/front-components pull request #9
Opened 2021-03-21 08:43 UTC by andruxacomm

1. [new] Добавил композицию компонентов табов со стилями

https://timepad.myjetbrains.com/youtrack/issue/MON-82

2021-03-22 10:35 UTC, NickJ1984 commented on src/components/Tabs/Tab.tsx
> +    const liClasses = cx('ctab-bar__li', className);
Для написания стилевых классов, в обязательном порядке используем хелпер `component`

2021-03-22 10:35 UTC, NickJ1984 commented on src/components/Tabs/Tab.tsx
> +        <li {...restProps} className={`${liClasses} ${activeId === id ? 'ctab-bar__li--is-active' : ''}`}>
Для написания стилевых классов, в обязательном порядке используем хелпер `component`

2021-03-22 10:35 UTC, NickJ1984 commented on src/components/Tabs/Tab.tsx
> +            <button className="ctab-bar__button" onClick={() => onTabClick(id)}>
Для написания стилевых классов, в обязательном порядке используем хелпер `component`

2021-03-22 10:35 UTC, NickJ1984 commented on src/components/Tabs/TabContent.tsx
> +    const divClasses = cx('ctab-bar__content', className);
Для написания стилевых классов, в обязательном порядке используем хелпер `component`

2021-03-22 10:35 UTC, NickJ1984 commented on src/components/Tabs/TabList.tsx
> +        const activeEl = boxRef?.current?.querySelector<HTMLLIElement>('.ctab-bar__li--is-active');
Для написания стилевых классов, в обязательном порядке используем хелпер `component`

2021-03-22 10:35 UTC, NickJ1984 commented on src/components/Tabs/TabList.tsx
> +        const ulEl = boxRef?.current?.querySelector<HTMLUListElement>('.ctab-bar__list');
Для написания стилевых классов, в обязательном порядке используем хелпер `component`

2021-03-22 10:35 UTC, NickJ1984 commented on src/components/Tabs/TabList.tsx
> +        <div className="ctab-bar__highlightBox" style={{transition: `all ${duration}ms`}} ref={boxRef}>
Для написания стилевых классов, в обязательном порядке используем хелпер `component`

2021-03-22 10:36 UTC, NickJ1984 commented on src/components/Tabs/TabList.tsx
> +            <span className="ctab-bar__highlighter" style={highlighterStyles} />
Для написания стилевых классов, в обязательном порядке используем хелпер `component`

2021-03-22 13:05 UTC, NickJ1984 approved these changes

2021-03-22 13:08 UTC, NickJ1984 commented
Название папки с маленькой буквы `Tabs` -> `tabs`

2021-03-22 14:50 UTC, ru-web-designer requested changes
![image](https://user-images.githubusercontent.com/3310192/112008973-0a778800-8b37-11eb-9de3-7e55cc96d025.png)

2021-03-24 09:46 UTC, NickJ1984 commented on src/components/tabs/Tab.tsx
> +import React, {FC, HTMLAttributes, useContext} from 'react';
Для совместимости с OTP репой, импорты нужно делать через звездочку:
```
import * as React from 'react';
import {FC, HTMLAttributes, useContext} from 'react';
```

2021-03-24 11:16 UTC, NickJ1984 approved these changes

2021-03-24 15:28 UTC, NickJ1984 approved these changes

2021-03-26 10:19 UTC, NickJ1984 approved these changes

2021-03-26 11:47 UTC, merged