Добавлены адаптивные стили для компонента Typography
timepad/front-components pull request #91
Opened 2022-01-27 14:46 UTC by mauta

1. [new] Добавлены адаптивные стили  для компонента Typography

https://timepad.myjetbrains.com/youtrack/issue/AF-380

2022-01-31 14:29 UTC, nikolay-komarov requested changes

2022-01-31 14:29 UTC, nikolay-komarov commented on src/components/typography/Typography.stories.tsx
> +            </span>
тут точно нужно было сделать таким образом (с background: black и padding-ом) и заменить StoryTitle?
и ниже добавлять background: white на компонентах?

2022-01-31 14:29 UTC, nikolay-komarov commented on src/components/typography/ctypography.less
> +      font-size: @fs-subheader-mobile;
тут и ниже лучше поправить выравнивание строк в блоках

2022-02-02 09:05 UTC, mauta commented on src/components/typography/Typography.stories.tsx
> +            <div className="lbrick-2" />
исправила [тут](https://github.com/timepad/front-components/pull/91/commits/97639024ff2634a326afcd6870b113f816e5a815)

2022-02-02 09:05 UTC, mauta commented on src/components/typography/ctypography.less
> +      font-size: @fs-subheader-mobile;
исправила [тут](https://github.com/timepad/front-components/pull/91/commits/97639024ff2634a326afcd6870b113f816e5a815)

2022-02-02 10:16 UTC, mauta commented on src/components/typography/Typography.stories.tsx
> +            </span>
сделала как обсуждали - вроде наглядно и симпатично получилось https://6037a031855680002369c8b7-tzvowxjdhe.chromatic.com/?path=/story/typography--default

2022-02-02 10:30 UTC, nikolay-komarov approved these changes

2022-02-02 11:09 UTC, nikolay-komarov requested changes
обсудили изменения в TypographyMultiple

2022-02-02 12:11 UTC, Volchunovich submitted a review, later dismissed

2022-02-03 09:05 UTC, nikolay-komarov submitted a review, later dismissed

2022-02-04 14:20 UTC, d1javu approved these changes

2022-02-04 14:29 UTC, merged